//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FoodCMU.Module.BusinessObjects.FoodShop
{

    public partial class Mon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhomMonID;
        public string NhomMonID
        {
            get { return fNhomMonID; }
            set { SetPropertyValue<string>(nameof(NhomMonID), ref fNhomMonID, value); }
        }
        string fTenMon;
        public string TenMon
        {
            get { return fTenMon; }
            set { SetPropertyValue<string>(nameof(TenMon), ref fTenMon, value); }
        }
        string fDonViTinh;
        public string DonViTinh
        {
            get { return fDonViTinh; }
            set { SetPropertyValue<string>(nameof(DonViTinh), ref fDonViTinh, value); }
        }
        decimal fGiaBan;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<decimal>(nameof(GiaBan), ref fGiaBan, value); }
        }
    }

}
