//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FoodCMU.Module.BusinessObjects.FoodShop
{

    [DefaultProperty("TenNhom")]
    public partial class NhomMon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fTenNhom;
        public string TenNhom
        {
            get { return fTenNhom; }
            set { SetPropertyValue<string>(nameof(TenNhom), ref fTenNhom, value); }
        }
        [Association(@"MonReferencesNhomMon"), Aggregated]
        public XPCollection<Mon> Mons { get { return GetCollection<Mon>(nameof(Mons)); } }
    }

}
