//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FoodCMU.Module.BusinessObjects.FoodCMU
{

    public partial class Mon : XPObject
    {
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fDonViTinh;
        public string DonViTinh
        {
            get { return fDonViTinh; }
            set { SetPropertyValue<string>(nameof(DonViTinh), ref fDonViTinh, value); }
        }
        string fGiaBan;
        public string GiaBan
        {
            get { return fGiaBan; }
            set { SetPropertyValue<string>(nameof(GiaBan), ref fGiaBan, value); }
        }
    }

}
