//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FoodCMU.Module.BusinessObjects.FoodCMU
{

    public partial class NhomMon : XPObject
    {
        string fTenNhom;
        public string TenNhom
        {
            get { return fTenNhom; }
            set { SetPropertyValue<string>(nameof(TenNhom), ref fTenNhom, value); }
        }
    }

}
